### ISSUE TITLE
Using -h short flag for —hostname gives podlet’s help instead of generating the correct quadlet

### ISSUE THREAD

**Issue by xrisk** [containers/podlet#105]
```
$ podlet podman run -h foo.local hello-world
Generate a Podman Quadlet `.container` file

Usage: podlet podman run [OPTIONS] <IMAGE> [COMMAND]...

Arguments:
  <IMAGE>       The image to run in the container
  [COMMAND]...  Optionally, the command to run in the container

Options:
      --cap-add <CAPABILITY>                                         Add Linux capabilities
      --device <HOST-DEVICE[:CONTAINER-DEVICE][:PERMISSIONS]>        Add a device node from the host into the container
      --annotation <KEY=VALUE>                                       Add an annotation to the container
      --name <NAME>                                                  The (optional) name of the container
      --dns <IP_ADDRESS>                                             Set custom DNS servers
      --dns-option <OPTION>                                          Set custom DNS options
      --dns-search <DOMAIN>
…
```

Using the `—hostname` full form makes this work as expected:

```
podlet podman run --hostname foo.local hello-world
# hello-world.container
[Container]
HostName=foo.local
Image=hello-world
```

**Comment by k9withabone** [comment]
I'm not sure what the correct solution for this problem is. I think Docker/Podman made a mistake not reserving `-h` for help. One possibility is to use [`Command::disable_help_flag()`](https://docs.rs/clap/4.5.17/clap/struct.Command.html#method.disable_help_flag) for `podlet podman run` and add `--help` back manually, but then how would one get the short help?

**Comment by ananthb** [comment]
You could consider just `podlet -h` to mean the short help and something like `podlet --some-option foo --some-other-option bar -h hostname` to mean a hostname. It's not great, but its something.

**Comment by k9withabone** [comment]
Unfortunately, `clap` (the library being used for command line argument parsing) doesn't work that way. `podlet -h podman run` and `podlet -h` both result in the short help for `podlet`.

**Comment by k9withabone** [comment]
I guess I'll have to use `podlet podman run -?` for the short help even though it's not a great solution since it makes `podlet podman run` work different from every other Podlet command.
