### ISSUE TITLE
Compose file top-level element `name` is not recognized

### ISSUE THREAD

**Issue by nicomem** [containers/podlet#47]
## Description
When using the `podlet compose` command on a compose file which has a `name` top level element, an error is thrown indicating that the file is not a valid compose file.

## Steps to reproduce
Create the following compose file `hello-world-compose.yml`:
```
version: '3'
name: hello-world
services:
  hello-world:
    image: hello-world
```

Run `podlet compose hello-world-compose.yml`:
```
Error: 
   0: File `hello-world-compose.yml` is not a valid compose file
   1: unknown attribute "name", extensions must start with 'x-' (see https://docs.docker.com/compose/compose-file/#extension)
```

**Comment by k9withabone** [comment]
Blocked on #63.
