### ISSUE TITLE
Switch to new compose library

### ISSUE THREAD

**Issue by k9withabone** [containers/podlet#63]
I'm currently developing a new Rust library which does a better job of conforming to the [compose-spec](https://github.com/compose-spec/compose-spec). The library can be found at [k9withabone/compose_spec_rs](https://github.com/k9withabone/compose_spec_rs). For podlet, it will replace the `docker-compose-types` library currently used.

The new library will be completely documented, conform only to the compose-spec, fully parse and validate each part of compose files, and adhere to semantic versioning. That last part is especially important as I plan to turn all the conversion logic of podlet into a library so that it can be used to create a web version of podlet.

This issue is blocked until the `compose_spec` library is ready and published.

**Comment by k9withabone** [comment]
An initial version of the library should be ready to be published once k9withabone/compose_spec_rs#1 is completed. Podlet can then switch to it as the other features (merging, interpolation, etc.) are not a requirement.

**Comment by k9withabone** [comment]
`compose_spec` v0.1.0 has been published! Time to start working on the migration.

**Comment by k9withabone** [comment]
I'm a bit stuck on figuring out how a service [`Dependency`](https://docs.rs/compose_spec/latest/compose_spec/service/struct.Dependency.html) (from the [`depends_on` long syntax](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#long-syntax-1)) should be converted to a systemd unit dependency. My thinking is currently this:

- Only support the `service_started` condition, suggesting to use, in the dependency's definition, `Notify=healthy` under `[Container]` for `service_healthy` and `Type=oneshort` under `[Service]` for `service_completed_successfully`.
- If `restart` is `true` require that `required` is also `true` and add the service to [`PartOf=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#PartOf=). Otherwise, add the service to [`Requires=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Requires=) or [`Wants=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Wants=) depending on `required`.
- Add the service to [`After=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Before=).

Is it correct to use `PartOf=` for `restart` or should something like [`ReloadPropagatedFrom=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#PropagatesReloadTo=)  along with `Requires=` or `Wants=` be used instead? Also, maybe [`StopPropagatedFrom=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#PropagatesStopTo=) should always be used for a dependency?

I'm not sure who the best person to ask about this is, but @cdrage, since you worked on kompose, what do you think about this?

**Comment by cdrage** [comment]
> I'm a bit stuck on figuring out how a service [`Dependency`](https://docs.rs/compose_spec/latest/compose_spec/service/struct.Dependency.html) (from the [`depends_on` long syntax](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#long-syntax-1)) should be converted to a systemd unit dependency. My thinking is currently this:
> 
> * Only support the `service_started` condition, suggesting to use, in the dependency's definition, `Notify=healthy` under `[Container]` for `service_healthy` and `Type=oneshort` under `[Service]` for `service_completed_successfully`.
> * If `restart` is `true` require that `required` is also `true` and add the service to [`PartOf=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#PartOf=). Otherwise, add the service to [`Requires=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Requires=) or [`Wants=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Wants=) depending on `required`.
> * Add the service to [`After=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Before=).
> 
> Is it correct to use `PartOf=` for `restart` or should something like [`ReloadPropagatedFrom=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#PropagatesReloadTo=) along with `Requires=` or `Wants=` be used instead? Also, maybe [`StopPropagatedFrom=`](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#PropagatesStopTo=) should always be used for a dependency?
> 
> I'm not sure who the best person to ask about this is, but @cdrage, since you worked on kompose, what do you think about this?

To be honest, we never found an answer and did not incorporate it with Kompose :( See: https://kompose.io/conversion/

There's no equivalent for it within Kubernetes.

We instead just have to explain to others that your application should be built-in with retry methods / retrying if it cannot connect to something / timeout instead of having to implement depends_on in a hacky way.

**Comment by k9withabone** [comment]
Since I haven't been able to find help for this I'm going to go with what I outlined above (using `PartOf=`) for now. It can always be changed later if someone has a better idea.

**Comment by k9withabone** [comment]
Actually, looking at the systemd.unit docs again, it seems I actually want `BindsTo=` instead of `PartOf=`.
