### ISSUE TITLE
ghcr v0.3.0 manifest error

### ISSUE THREAD

**Issue by AzemaViator** [containers/podlet#82]
I am unable to pull ghcr.io/containers/podlet:v0.3.0 or latest
I can pull older releases, but it seems something is wrong with the most recent build.

```
$ podman pull ghcr.io/containers/podlet:v0.3.0
Trying to pull ghcr.io/containers/podlet:v0.3.0...
Error: copying system image from manifest list: determining manifest MIME type for docker://ghcr.io/containers/podlet:v0.3.0: reading manifest sha256:284fb19670b144bf507548406a07b563077d419de335c685d6d9607794596ceb in ghcr.io/containers/podlet: manifest unknown
```

```
$ docker pull ghcr.io/containers/podlet:v0.3.0
v0.3.0: Pulling from containers/podlet
manifest unknown
```

```
$ podman --version
podman version 4.9.3

$ docker --version
Docker version 26.1.3, build b72abbb
```

**Comment by k9withabone** [comment]
That's strange. I deleted the tag and re-uploaded it. Should work now. There seems to be a bug in `buildah manifest push` that there isn't for `podman manifest push`.

**Comment by k9withabone** [comment]
Ok so it looks like the `--all` flag is true by default for `podman manifest push` but not for `buildah manifest push`.
