### ISSUE TITLE
Converting docker compose file does not append necessary `.network` to network names

### ISSUE THREAD

**Issue by puresick** [containers/podlet#90]
Hey :wave: 

After setting up [Penpot with its official docker compose file](https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml) I wanted to add Quadlet systemd units to keep its containers restarted after a server reboot.

Using Podlet I converted the compose file, which resulted in the postgres and redis container to fail starting properly. `systemctl --user status penpot-redis.service` gave the following error (it was similar for `penpot-postgres.service`: 

```
Failed to start penpot-redis.service.                                                                                    
penpot-redis.service: Scheduled restart job, restart counter is at 5.                                                    
penpot-redis.service: Start request repeated too quickly.                                                                
penpot-redis.service: Failed with result 'exit-code'.                                                                    
Failed to start penpot-redis.service.
```

Unfortunately `journalctl -xe` did not show any more detail on this error.

While trying to understand this and fiddling around with a simple quadlet file setting up redis, I notices that adding `Network=penpot` was causing the same issue on the test quadlet file.
Researching a bit lead me to the clue to append `.network`to that line resulting in `Network=penpot.network`, which solved the issue.

I assume this might be something getting lost in the convertion process?

Please let me know if any more details will help solving this issue.

System Info:
- Fedora 40
- Podman 5.1.1
- Podlet 0.3.0

**Comment by eKristensen** [comment]
I've just had the same issue just now.

**Comment by eKristensen** [comment]
You get more details in journalctl from root

**Comment by k9withabone** [comment]
Oops, my bad. I'll fix it for the next release.

**Comment by thehabbos007** [comment]
Thank you, @bishtawi! For anyone on an older version working around this, i ran into problems with aliases not being properly handled by the workaround, so i suggest the following for those cases. But obviously since the fix is in place, it isn't necessary in the future
> ```bash
> for file in ./*.container; do
>     sed -i 's/^\(Network=[^:]*\)\(:alias=\|$\)/\1.network\2/' "${file}"
> done
> ```
