### ISSUE TITLE
Converting compose file fails when image registry url has a port

### ISSUE THREAD

**Issue by vaahtokarkki** [containers/podlet#91]
Podlet fails to parse image from compose file when the image registry url has a port defined. Reproducible with following steps;

* Create `compose.yaml` with following contents:
```
services:
  test:
    image: ghcr.io:443/containers/podlet
```

* Run podlet:
```
podman run --rm -v ./compose.yaml:/compose.yaml:Z ghcr.io/containers/podlet compose /compose.yaml
```

Following error is printed:
```
Error:
   0: error converting compose file
   1: error reading compose file
   2: File `/compose.yaml` is not a valid compose file
   3: services.test.image: invalid image tag: image tag contains invalid character '/', tags must only contain ASCII letters (a-z, A-Z), digits (0-9), dots (.), underscores (_), and dashes (-) at line 3 column 12
```

**Comment by k9withabone** [comment]
Good catch. I didn't think about registry ports when writing the image [`Name`](https://docs.rs/compose_spec/0.2.0/compose_spec/service/image/struct.Name.html) validation logic as it's not included in the regex of the [spec](https://github.com/opencontainers/distribution-spec/blob/cf9023d6d9682190319d04a1a6afdbc9cddd265b/spec.md#pulling-manifests) and the "_Implementers Note_" wasn't there.

**Comment by k9withabone** [comment]
Blocked on k9withabone/compose_spec_rs#22.
