### ISSUE TITLE
Support IPv6 address enclosed in brackets for `ports` short syntax in compose file

### ISSUE THREAD

**Issue by TeamLinux01** [containers/podlet#96]
I have a valid podman compose file that has these `ports`:
```
- "[fd7a:115c:a1e0:0:0:0:9f01:c080]:80:80"
- "[fd7a:115c:a1e0:0:0:0:9f01:c080]:443:443"
- "[fd7a:115c:a1e0:0:0:0:9f01:c080]:443:443/udp"
```

Starting the pods with `podman-compose`, it binds the ports to the IPv6 address without issue.

When I run `podlet compose`, it errors with
```
error parsing host ip address: invalid IP address syntax at line
```
the line is the first instance of the IPv6 address for ports.

Not sure if I should be using a different format for IPv6 port publishing or if it is just a bug in the parser.

**Comment by TeamLinux01** [comment]
In the meantime, I manually removed the IPv6 addresses, created the .container file and then added them back.

```
PublishPort=[fd7a:115c:a1e0:0:0:0:9f01:c080]:80:80
PublishPort=[fd7a:115c:a1e0:0:0:0:9f01:c080]:443:443
PublishPort=[fd7a:115c:a1e0:0:0:0:9f01:c080]:443:443/udp
```

the container starts and publishes without issues.

**Comment by k9withabone** [comment]
I dug into this a bit. It looks like the brackets around the IPv6 address are the problem. `docker compose config` seems to accept the address either way, but it's not specified in the [Compose Specification](https://github.com/compose-spec/compose-spec/blob/231b09c30d339e950c0da17fe5bdc793366b8fde/05-services.md#ports). The only part that mentions IPv6 addresses may be enclosed in brackets is the [`extra_hosts` short syntax](https://github.com/compose-spec/compose-spec/blob/231b09c30d339e950c0da17fe5bdc793366b8fde/05-services.md#extra_hosts) description.

I'll make an issue or PR in the Compose Specification repo and also an issue for my `compose_spec` library.

**Comment by k9withabone** [comment]
Blocked on k9withabone/compose_spec_rs#24.

**Comment by k9withabone** [comment]
Created compose-spec/compose-spec#530.
